---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCFRV13rn5AYZ29KbaXtLNDoAzJCkbMIrtM30rKptBM2hhZJkvcUzjDWrKUXkWR36SKpTSArRwrR6mvwjeB90F1wCiZSb5DInNTWke5JzY4234fB7nNEe7wMOooxHnqXuRtYVdQS1iW/IJTVoZ/sAP1nvtZhJGXzSXh02yLW4fpV7QLrnWEMBtNOopdYXX5wqp1Gu0UP/0irHaUMVqRth9mL9EIXPlnwksWMAjnJ3gHvb7t+60AGRoBFL8pb+MUnK5letIuVQWdPvK/ce6mcwP6BAUNpvvoX0eV4OopJkZBLhE5gw9U831evEW1eRFbq6TLrQXCLjQHUpmdIF0eqX15ZqyIJMHUCI1rKSH62obLdy5gsNfag8mCdSjf0fABy7j72ccwAkxHvxfoNXAttcZPC93d3hP3DZw8uy8mrXm3hr/bl1Plwx8eCwViMYYiPffpheEtDSGFfvOZwhjCM7GQfVwo6PuH/AxQUUuH4nnj2HrxdsAnCacFZqfGHWDSB1980Kl8hWpQdrrWS9AQKy9evuUHLjKoy49bv6DpXfvLYATv9+IQbfkqD7GsfDwGozaC2Qz4u1KDCMtou0nWC3y+ewZUfUs3gpC/sQ2/MH41a/ZQ7lNdIAnopAY+kKdwMF1Q7nd5dZp8HDtyZLIxqaNo7LUgQg3oo6KGSz9RIfBBzjtGQkSYySlqH54/ixyEQIXS18eNtJOBZugl
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
