---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCfET2Ot8H3jCoT6uDUgi9TvO6gFk0z7EJTDpUlqwvynp3VWEsBfE8v18i2QChsmL3MmijFdLgH9owpe+QM8vZ+mJE16TdxbkZTRwPXB5KDuhoQY2frYXhRTOrF0cPMtY+JNXPf6YepwzOPPnvXkUSRKlevODfgpNN1M/LztN+qyUrQm3xP2uX5gql2z/fLy+OKje30AT6gMkO1Bb+MHUGlQYLLq2POsOSDiIuwhzjkU4C6FBN3vnm/lZ3YLvtURlzfKXDkA/lSxWbgpXU+Xhhc0Gb7YI5JKX1Adt+9QYeGW1qysCcIP0heugEtW4tvm8TtA5AIT5RVf3M/X6d4jOsrqBV99nKZd6UrfK4oX92vXObAOKuZajzjfvc/LRQNvTNA8JLjdYq6rWrBFEiznDPn4mlnQ8OOhdwX+oMYPHniqzV96Aw9++BYmr9ze/C7kTBGFABHt1e65foQGB4CZanw01rm43zu0FTXWW+JujJizkyf/WnD0lg2+QnykBFo1Cvw7TqwEwWGFQQOhTqk/Fm+XFO9lmUp3qKMuHeD0xlA1WxZ3wiFZ9eDwzsC/FZLuPRgV/uCEcBVLRKRKlowbOn35a2y8aJP4+4UIZgDxbwRS4qkrpRC1UWXowDr6ZbyxZVSw+0m/Risyn6HCumLrjf2AJuylhVIYR4Nw84lX8Bb2J4Mvdti/4kS41LA19tzKwgIjDR2RoOkB4jP
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
