---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAGaZdw/voCswYL+o15Ie+FaK8kaw29gMCsx4mtbklUnddQ034vHVShvRXcZ4o6RWLLzN4XRW5iUzAq2BguuwUjE49wZYiFEACYO11wmJe2u+O7VsypFpr2laIDhLB8lDWecBn0w1OVGX/+MqVzXsFrth9tx2VK59oa/oxZIQEeuSspD8IhkJVOtfnSbfvMhS4vW6qF4zy1Y5C7YfZhybW47M5+COFPvCXGgERziMMLqfaOh377QqOooa2bUo7/0phvpcxb4LFunFH1LHUa2AWIdZNefglsBV5RP0tGZmiXKhujdIGBR6KUhbsB3L2cX2rx6wgISI1WfT6he8aFQTDTcH0MlqwoB2jsSJtPpfCVSsZw9bYvFqxgFVOEQ1r1cZGmVYRnVsp2GUYYGWFA/yoww41bpeaJMTEXSgCWk3/579q0yuVj4far8Q5kV6e9NJ2FmcqxyPbJpOfxhH7xzUsngQS7Yu5usej3BRuIQHolIxXa1PWuihBv90RFx8wsEJJD6E9UMHo8sL+FaHJfAhdUCjZz7sWNhjo5uCSn+vIiGYNSBFOsYAPyy1cBsY+kZVPnJIffziCD5tgzulZEmNEh1dWiU0ZbY/NoQOokiuq83DWLJObaTdelJt27m8nRdWpq5QylNj3XJTYKFP8lfxCR8ktnH0SBZX1/GEQDPIFKHnomGcXl2F/8+1VyJW8SQ57Pzku9CXQkDJUL
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
