apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-phpmyadmin-phpmyadmin-deployment
  namespace: mariadb-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mariadb-phpmyadmin-mariadb-service
            - name: PMA_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-phpmyadmin-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-phpmyadmin-phpmyadmin-service
  namespace: mariadb-phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.11.75
