---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCkZkTCKsXI9pPkEuLiS0hrZx7pFvYuRCPF8S0s1xznmERaUYXkj0UoLs2nuS9pRYowtkSzXezLUFBw3YljqcPtf3bTWbK+mCMMA2Y3obXTslgN8P04ZBJ+ot7/JhpnRxveLGfuU2GdrMxeKA2H8X1xgjbp1cN24svdiTy+a7FlZ5PQdVEXpKUeEvhsZzBqYYYy/WG3+eJmt7dQBlULPvNOtyUqhztAEsI/vOoIMuOxxKJdNxxh0iB/CuUpSv9bAUaiCfm9s3hdp4SQ8z+uE/GoQozJnpqaxG7TPmhxrk83skT7YwMakfAuySTKYraHvH9yjUn18VAb3Hp363clpW+x+4TNdSLjq9hJcBEDyrSzQZJDTtiQenZLPwkhuL3KEOrLE5/t0W0ktVvCarQ+Z/vOXBQJAtetQ3y+7ByfMQKSgrskrVFhdrwdVVGVs+cAyIjkgNqI8s4M2jXITVQ4xL2nlKe6QgaSualacuzSagXNsF+fH4K7ZwFWGQXflsO19KKPvRpjA6h5Htup43Qy60QbgpisvR5dIQ6fQDH63Kj2pga3E1IHqGjSRuLX/Pc1M9k1zvGFxAyPutXjGQeXFTlxnHgH9WDZHu7Vx4FIZKBoTA5OAzQwm/BIzPb71vcRKbPEYhtL1tfkP+HlWJEhyAek6/SU8NpitHER1fkUGTGfBkxpW2XBeMqvNV1K7zMMkEtOJQI9XA2Jh/GL
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
