kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-phpmyadmin-pvc
  namespace: mariadb-phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: mariadb-phpmyadmin-nfs-storage-class
