---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCfgTz9vzuRUaR3rJTFDrheRHngxnx0bsapdIfLdiatgOfzxGZr6/qxmR12HbJFpv+YyRjpckKrqZwau8Oo2BmE1KbOauq8ci1EJSFDbTro5BSsSHgD560anoFVjpfZtNhIhaEKmcESSIJnoEMuVSq5RwyqmzstgOpHGsUpHUb4ap4R/LC+kuTmgOu4RhmwKsQrzPQXPjj+RePVEQbYLQyNnCvMmMAaPMbEFc8K3hRuSredAjwkFq3st2BOOYlpBudCZ899t+igyIyXZGtZbfOE9rcRq8xndGvNu669vjN1FUfXls77GFsxsI1vwGr451Tm7IhaM5wqQnZlN4eZD5xDmf9e7hvudZ6qHiWGwcNA/CN3dE74qSP5rAgN21aJmmz0aeRvHPsIzqongoclz0ohJZQa+FEIqV/EbB/vycwQuz7S9Cyfhh28Xar2tfGV/cU2naztJ75cA5eHxZ8a33gQ8mdXa9PVpZEDi1MKkRdYeR1G+6MOgVO3PQnW1cvWWyHD9NOKDTwsfYNR1vi2qkeUPkCDYpfFJRdPmGN9A4tzTgtFW6ctXRNz5ewvv2AOk4iN30c7Q9CD5AKJ8QcdbRixiTCA9bJ+y4IXdxawES5ogPOJoCADuTTbCgZVR31a/Ye6VUEs9HzYNRU+3CSdMB8C/s/phf9B7VnvBpB4CXl5A1SsQeQ2a0qY4l8ievDJ/xfBF4JNGMhOTJklIsnwHYxgx+7UgiJqq/q5MBl+YnefWuGG9cX2+LFtwaYy5SwCmqfPK6kOdHiMsLlg+H1uTr2RU3bI22gIlem2lekRyAlFAh18rdmjSVDD6trGKi/iL5REY/VL82sW1nDNG6q5XRKw85D0VfgXbOwOUh3JVJIAYp/Qs/R9D/1JdyfBw++sl3Orta4oOZyxYNrhdq3GXw83qs/p7IPWJtn35HMirF3RJZICM4FUuYfV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
