---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgAaVRqHZ0PfBf1/HfZ3q1QCItzZ4iNi8J31ejAtkA3risnLedL3b4Wui2AsKRDReNNEDy6JgJn0syDbPswFmgQLF+3foa7RYp5yE8t3AkHtK5P/EAy/iYCBJLvDlV6/ecoDZEvjLMI+78RZ1eciQZu1EeIxBci6NsrPMh1RZG/KQ0dOROi6xvesTbVDALfXustx4E3Yxr8SPr5GFLY/uzjddEemXZT9AhQGS62OqocyvHCu9F9M60TVwofEPzflD35UA9aRbUhTbpAK7FiXnQ69t8KgvDKVtZXuun7fPCcD2V5u64fwhIeNth9SxIewCkN1dCUBRFUPQVN+lTME2snO/uvQjHHpRmu6t8Ws2Y0przPa60LTk+LEKmILvIhnSHHE37neU5xQeYa6IcCPU+J4yRa7s4JyHgCT3PfldvPmhHlhYepr75nTICOFwHYkcYhnlGuO3lFT3dwRBoJY+Ku8sJBDUOcILosqikGiZoNQzhyZmlfGwOpUMtQn8GSfScEtpJrqLLJCmCZrgqXlpLKGRz3nWfwKSFjTq44danHeB2R1QRzJacJJfFMe/RHDlsYPLky3EWvqPWzA1Ec3qzofqlTYtaMWyNrrhGejweyR/BPY7LJAa+oGMiGxJEinOhOa0ZsoCFNpFYBVweZvyrRDYMYVdXJRM31LqErnl5R5xWUOO/i4REVz++GNKEb46xf0gkrS+aIVnwBxWBZfPFzIToXJkUJtvBKR1LTcdH9zcJOIz6rVsZguHUSvdzmJuOgr6IZL8yrueNsUDAbs04g1422qxL+Wofc7p1EgHORWdbZe53sd9aR35i+bIGVSPlZWSS0TknGK/MZnXtXljoftsEwt9Z3wellw68gQvK6f1ckGAUYSBW5cM+N978WW/hYSqgO1f7udNt+4v5+x5Ug6uUbWwNS6a8Jtxc/yARaExjnFYlWFUd6G
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
