apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
type: Opaque
data:
  CLOUDFLARE_TOKEN: ZXlKaElqb2lOREk1WlRNNE16azRNbVpsWTJRMlltRTFNR0U1WldGbU5tRmtOakkzTmpRaUxDSjBJam9pTldaaFlUaGtPVFV0WkRKaU5TMDBaVEF5TFRreVpUY3RPR1ZrTkdReFlqTmtaRE00SWl3aWN5STZJbGx0VlRCUFYxVjVXa1JKZEU5SFRtdGFRekF3VGxST2EweFhSVEZPYlVsMFQwUlplVTF0V20xWlZGVXlXVlJyTVNKOQ==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBTG7L/6XFbKLSJC3Ym6iMa/zc4eeFuOlMfCoYc4rusFHlqRafmCfNWtQDjhB12s13GCQqmy9imlw483+mJYYDk6+O7TLG0c2YL7XsDD+L5N20+e4mRyBJPJAENygZpM0H5VVMKHsNIeDK37h20QSvqdDs0Jznx3JQuy1Lm4VT6TqrVS+INQCdzC1BnLND2IFBZeFogFOAmOsKQWyHRAeAVJ/y5Le4nXLFuWdI8wKIu9CplcDGgjZ86ieOGz0zOOv4IdAroBA7SWGk4GIBVlgN1ff/iaIJJmdXEPbllNrev0r2tkcNmSh7Wus68gvdspbxHb8TmhJEdtvGeYj/tMwoi4mr+cCWKvFcVo1+oUjEE0eldw4UdbTfEdZdQBt1ewmJWH4UL6HejPNjU89P56Tn2RBN5F98rpdvYx0iDhIZaoflfr2rFRnGCrtZNfg+Kv+JbTqrff+V35W3ohbFn0zdD7/gDST1zN0cMR7034MLc0RHLEx2FajCu1uNmyzd2B6aOEtsU0hHEvFH0vakuznnIYcZN7HlftXJcDb6m7wSzAjY96vJhivrusMSLZ4CSnkzFn4DXxSNV51NTGwC7I1pouUs8Qm7akIqNjCtrnCOeIJBGIdL3rmbski+KPj2cY7O/t1G/wHWR5Vew82oxH0kUsNA76NS7FkMtiFJR5hzS/S9bPDMZKQSbqBhu+JPQRZLth9GkqCjUVKz8fkGNmZnm8l8gHa/hs0Fiq66Vt4M4XU9J8Vavli0r3gcWT0udisFGeI6fMjDWJRY11kMTDojYnaZG2HS616VmeHdezrSTNILhdgpYYgoP0o/KVmUF40gnx5EdyMnQ+8IZRISQhkV+oiZLcnwvvFU4t95XKR1J6/moYOGBaEDh0MeDQnVUH+ySbqjR09InBQj4LzvvHDrZhQKJzNWJnZCpgOX/ofP+2jpzCc/ACqmF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
