---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: WlhsS2FFbHFiMmxPUkVrMVdsUk5ORTE2YXpSTmJWcHNXVEpSTWxsdFJURk5SMFUxV2xkR2JVNXRSbXRPYWtrelRtcFJhVXhEU2pCSmFtOXBUbGRhYUZsVWFHdFBWRlYwV2tSS2FVNVRNREJhVkVGNVRGUnJlVnBVWTNSUFIxWnJUa2RSZUZscVRtdGFSRTAwU1dsM2FXTjVTVFpKYkd4MFZsUkNVRll4VmpWWGExSktaRVU1U0ZSdGRHRlJla0YzVkd4U1QyRXdlRmhTVkVaUFlsVnNNRlF3VWxwbFZURjBWMjB4V2xaR1ZYbFhWbEp5VFZOS09RPT0=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
