---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgDDib4399LjysOTCQ9kh42HFcClBQydC0BXVD6mLjqGmavTZW5hoFDDTqsOfhsTwi+OSWfw+6lJ6VAGLzoJOLDxFbHQg1BNXOFovsbm8HEQHMmN7p+jThb5nRIMR6caTMVhF54FcN/CzORXhbG3egO0HSoCXiVL3t+H9xh1fhMa5pletgRl1h9fiY2R2L2ZJyKwDphoPZNi4JSJxsnudnvRERWlIW9+aXvSIu1KOcVOZFt8+LJViSXTKHXVkrgiGArtipEPi3o7JW6PpEXplNr2TZBoeR0xo0XLAlpnx0CrPW52GkdujMeqIuZK3rFsQrvxKm+jWkEHGcC098MCW7A2zC1a2ZB9ftZSBLaZxCx7FjXb0+VnXZY1MSEuGPRPgHbXuMpZeM9lZd+wLa/58nvT/G9s7b5Ri1gcJlKrvvXuLOyADL7RwK0OARSf5kXo0tPjnxCO1jrgMzC9AavJ8i2CTSEdx1qCnfHviRp1qRdzNtQG4E+sw5YnMvze8BYgdLhEnWUDU5aNoOXVxO9TlZpja8Pu5i03YXubNbGtWglQVrQTe3K4/FO0VopmM6IbkNj4PxrismGf9qvxQrBpgKm2kc6wN/lXER4cBiXdIxWHTh+gckNQl0o4GHaULAK6PEGs+Ort7kyCHnq2HVGRjKFmIwQjBILB/B0KDCLMKM0Bl65NAx4UVQyKBdNjahxGnsRnI2wpt9xExZhyNyh7KmoMRpQbQG7EcDrHrJRds5rbR3ktBnPOi1EhI9gphDmKJ6z0qG04dhYUR1i579GV9GYgwRPH6395/yNPz3bfUhnbZcEYd1Rbhqlomcx64GvFHRxBUlo30fXKiZQMf+Dk3f5yT6yAMvJrsvI4M12tbRlwjGXX3jWKKw2bUrbNleTt+Zajs9cdBF067Zd2F9xwrh+t743VK2bp22sAiBc1xqeDiK6hLD0/CYWx
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
