---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBSoFIYxNp+MKRhjaFdqaVYMu5SE0Pmx7T+7+i7UO24Hs99BN2AI+27jHHsmasS9D7JLvDqO1v6LD5M6GVVoEkYB+eJUnIoIyl28iOyvuuH4hrBumbiZBjdfybpBzHfkfR7aPpaOzbGfr25P3zG7ZfLggSasOIxQ4TUB0gTmPNWsdwWEjrFMDRN5G9zryn+jVqc63lIIHfE1/lqc29Cik6KfSyjglke/wv4lpwOGxq8nUrJHyULns12BC8subeLDKdTX68xlyrDP2gwxqD89KnYy2did5guT1k6sh7i5PtAc27+cIIs8w3WyhS2bRy9sW45PmRooFkQPdRt0m8AwA0KfnD1iD5tYymcx3LSgvDMWprGr8s1FDrzPx8GEHs5qw/51V/XbFxt9kd9NPBEr9w5866NunT+9xVRAEMn06Mf6Vbc3uPMLyq+FfHhhooyHME/q1VGZJDQQ+ca7jli4Vwa3y4ZwAS0SYZmxFXRYlZ0M2orq6XJLzewXZz1jK0+ohfXvFG8zD2wAlNs/iNwWlDID31OWzwQfBrpMPftpyETEG1fdj22tu+8xbjZANbz70e8Bd52MKmzwLgc47HqJES7IAYThE4l2RVvWKiyIWvTqIhT8N14wKM9Xv1hQ6GIte8afvHAgtFW9emtYkkezR0tbfFk7Ft/cfzkqxKn5E2tofpQfz3ShdHKZOZwaNNMPUcFAgpVG1ct/orEJFt8t0resmqa0J0MX9127vXRH0GV3CrGw+oFLAoG508fKCmIA9ZFYCmp6Z7hBG9rh6/8baG1VD9bVNrNOKOrJk+an1t+EHUNgQyBToIJjRvuiEinuAEdfsCcxQfKWkIFQuWvbwZKkhhH6imAGetej/LxFSfPUABE1B16WFRyvT2bQ/0nzrhhUNO0sYX0AVtPmker5LjEsi//ITpNega7Z/Qwf+5ND8RI85xywUiT
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/instance: cloudflare
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
