apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBbED9dvC5596X2yXC2j05aIixZPSIEsWmx5cN/G5sYQM+malAXxJxEruFbYMJBBJ52s+bo84ahAvSw4gXjHCwhxnXlprfx1Sp0zIdOSlvf8EyrJtLWcg3iV+BLdSKhg1r880jpbtCucjeXfxX7ZJRGLMdcnJIkSRHp9Pm1asqjQrdOc52mAmFq4fqEOLlSbJGimztfVVr+TVVuAKPIOsPptM70HmtRX8bvxXWe1y88/0IC2T+bo4BcEUFzWv+rimrsBU1+9dcdPRkuInpwqvBfn4kdGI1N4+vxJIUNLRX4TMHrMuhRQY+A6tQbIMbF0WgHaPVxpr+Bx/vsZYmohQXRqwsSECb1NMlFfg4zHRXHmBMXRHuvxT7lxagHKHGFCypq/1M8yPQkCKdOBzNSXNKLYhurEFqWDeNwaFNY6PXpyt7YjqA4bTO9R0UN1SaLH1S6a3H7DOS6lvAyzgrO0U5lDioTz6NxL6JrSQRO3lWe09HJqaS4sYkRcHH/vmrLdjuBvFRPakHtYGJgc2ESulVWDsknOQDYNKlZXR7Tb63LZRvREKgYUROplwC1qT5S0DlSdqDc0PqbnlX7IkjRoPVmMr+AbAymGFf7ULv9vm2QJ5a4ibv2fHA7gbnsYQAthm9SeUICwlcwieCQgUJCwHzfAsrUcfwWko3/9QO9B2RK8HW1vHM6gE446qCnjTjTAitrjczbpQ25Uxa4gS3Vo0vuCNLbWC5fomL9R+KfaUnSir8gcDOpVofBH7Z7TlKe3hhTVwWrETubDAuUX8yQeMUN/YeUNYxYOL1ssk8qptOJH/pwnSbkCkl1IKCyvGFIFWmKWuAPNR/Rmq1PmZ04u26ZpIgTbOrFw0tTptpBuBYOjUNf3iUXHzx9q1xjDjPP7uD3vNsvSNo5Od2LcLkj16V0MjUNI8/3PH7tAXd4mt9EvHmXO+YkbkUN
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/instance: cloudflare
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
