apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgA3P+OQlu2ThjSDK+KU+G9vvz/tpZeSoAPKQKSYNoDHW1NaN48fPz+SB8+wCJw9DYrT8jt80cBJTu5hBtiVlzdfRPXZywI853lFUQNVuNF2IpC1gpYPVxnI6+9nlfqHQSXlZBNjD+74R85UtvUujwgZDAt/7daSj4jfu9OJl7SzZOpFon1N+GEF6+cQ8Bcl8idyODrsGANoVaSO+j7TaN0RnakLO8FUNMEB7KhIPuGT+KMb+pVDq+OzyLbPAYHVeXCGmLmvIQEtsLVdcfTjC401iaOTJxs7RHP6nAMx6xM5mc8kZ6YQdoYJJEzj1XIDPeu2GTzsqCu+cof7VYRyarHX4+ouPHiNh2F5QntLttluwCHpnFqovNY+QHh9Z+R6EMC2+wTJ1NlZ/eGdbb0asamQ6qkie+CvTmEK5xD9bmcltpSqffOnrd3+ro4LHhApcqmCsPDVdC1oT54uB3g6I7+soRK+81hu2CMsU4zBH3CxfPIkzpov+FrZc5iWDEhn0Ulb5KuN7wub/cixtFwr0QyGtjHThRrbvRsAD+3YmkoKicoyuwy94jw1iD3UTafwk060jI4X5ZkqgEya1T4rDMxUmPEE1tEueEqDXvOF39XdSzZ2GX3xcfTQObpljzvajQkx9w4+IFVGWbFQws0bX83/uwio9oGnh9A4X72d/F0eflmNiVT2gMmauFQ6bgX9EwFRwSSd/ODlpcr0EDO1f5IJ4hHk32E3kcm13juC306AkJWIP3Jt3sIPosHdtnDrEesLuFmYqFjbnZs6SJlgGsMvUKD54VHu1Iw6ZvBk9ZBGwg5zONaYQB302ziKMAYSs5yfsilc4xqFaHDaZH5EwRYu7fZkbO8PzgTDNd4/dGgmMbfRMBqTeLBqvck7MMifJn43Rn5AY7wtWMHZsWRwmDQMmRkTVSQIxVaz/70B7ni8ZjoeVsmsMoMj
  template:
    metadata:
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
