---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgASgcCX8BE9AOCAxW2tLRV7t5ao2pUnyRCqD8BeNCAk394d/TnxLuYE/zGO2SyMXWugh2eUXBIlroTSJl2rDs1fxUtJRep5XbOZc5gjwKk578BZKr8pwtkPWuxScPBqeAofeOHZ/NXDbN95fXYtA7hUcMVmjWAEQbWVI7yuJyVX2mLNTYRu09iirIxcw+Zj8Ipi35k0nfZWcnPLBORRytww3NZXhFGvHEZWWb8vfpDga2KKo/etJTNa9msvvOoHvhgpqrvtUL5TytCOEMjrVrZ/9sfabTuRySDoFxL3dSOcUXC4wcjNX3qAuhwA6RWlGwwZBAY+MaM1n+F71ZM2/+e2FOLR402M7J58XRvmeAo78RL/h3LNvc60dwrtdJ1qZpr9ZGi8hCDyP5F01vzc7r4OnPt6XAZ0uPuHqOePqS93pY7Z9l7nWF2MXSGshFhyGxV8ghU5e6kcxUodlIVF3e7Kb3xiZMLYt33IHz5wVxGFlOoFX6/tmi/gQcsHxEn6gNDD/lPJgu+lMvv2T/FsCDEAN2gGgF9WB1/iP++kkJaujo3piGiGt8ni1JrFcsYmbQD4I38wtbZhtPgP1jVG36QDGfJzMBr+A4+OvYu9jlwj9bT1/mi/VIt0uL9MfQQq2LwuHH1OSV9MibhAwn3MrUrT5YDhrVYG1ZzdaCsTzh6JRmcJNPKRjFF/b+jOwGi/Xh3P+O9aZvCYDiliiPC4EzYdfhxM/JHF4I4QjPLi3TYxim0H6fdwCEI3l3SlwH76faaecEbLC7ot4SB7b1fiKKGXaOpYQhJfb7d9Bj4SpNlu6lPwpVYsSdQwAFoKpEDZic3FyTQMQwdsdf1W/wCqpulCGTaaVr0OPUhjD1iT2hOl37V+Tnls5sEJ/aTkoK5QBwHgkpXOM+LsLIqMXo6g5AW7qwW4moNZVCx0jyR7ZS4mrgtmWGoNavRJ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
