---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBQmdpAwYZU4FkLSi9Oh2ZAPOKhNk//d8T3Tko5jGkWhxyltHsjJicG2Pjyk5kOntrwCEXM01mX2dMdASAfoatxC1wTrp+vsmMNhVNfvEUdHRJ4atabTYquPjVhdKoypNTy/4JSQyxV9blAgFR969dUdUO0zWX6CGu3n+Hm+TANygR6SeoVLb4Ic80f1Sjp6zF64obLe+AxEwh4a6zStwThp2xk7YqLYcBSRPdJxP9qdhDG5nAXqQGssqZgoR0zLSZU/+5tdH40tbX+bCZoxGHINPlYOWlqap/r+diZpoLxfjBG+UI6VujKfJ95bMaBc1QI5FkLV1nI0NhU7pvUH5Tlo6UY0Oo5itG8Z6ZjEZuTzySqqMh6umD4pJqX8pjHSUhZ/66v1cTfOQw5K/PHniCvLqkMOtiAf/ke6teI7JMCAUEDynwyqIeoy8ecBGhisDwm1/qkjuLBkQcHjM8De8qhX/LCH/eC+W6YSQB4pi0TnF8ieuE3eOXay/MgyYEvVCZakDLf4gRTJUFZjYnWJcRr7eAUUzenFZV60zdFLXaNu/KPwNaqKt51rO2xegeZv6Me9qX8XasPda6ej8dsSC0DptmetonhXfFo3Pwvh6RS4Z1GEK4FRQsXsrl4gPLf1CM83x4ngFOjtn6FjaOHWUvFoq3hJ8nG0kRq2FW7GNolx0RGI5crcdr70RJhz/F9IaUq7TMm9NdEzt6B2rF0x2i24FjU3gClDZW9vnCXU5U1Rny85NF9A1CVMNZ9lHk3HnsGYYgX91wBuz1HIFz/6KZEp8iNNiIBJeCYGENKhT1UpxGJEzk5rIxDnzxvMUGF68m+wPargowh5hY73EK5YfKRUGq1E4DQ7va1PyEqh0inR9TQw+9RSQm2aCON1qiFdOj3vOluzwk2YZaFqt/JLYaRIms63iFdFBKpQqixFbBBVKwF7Ah51yZH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
