---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBghWKNOx5rbFydgAGVXXRoTW30NP7nSZDny/8GdPC8cgoYMnOhtiOQyKFoJd0hrgGnsJ90WdTHZwJwUZ3TMqfHj46GMy3qM1eYoWzzHWlGnRObzyXVc9E3X0el2/XIx62YLtgUwkQsmJFaf9IBJI8vruKAA6T66GxaHA2mIcezaG+Htuyg5FUcgx4cqrPFhmL5jGOoiV1unCA2bSUFWfsFYx5PTp0jaL3Td8zWN7CBIdkg2j45BFd1NOnk+GNMcJ7JKE4vX5kJbyh7E3rVw6Vkmo1Y3O5QclRSboB0jkMcuDHRaA+xTAW4gjF0R3XFdpPql62Lc4F8r/HuRAuDGaa6WxknZihQ2A9OCrlufU+gDJhrpBkWRxWC4alUBXf3N/UmozZU9JQUZJg6j5jY0LPvqX2CdqMqW+A+0Q8dJAp1t/bC84tdhZunWALmfbnY2dLBqM2eWfL/CpKCD5wPSqLufagwSHMfK0jSqKT5/TkmyBqLh23vdFk8cY6DEwBFp0BWZBeOeNsiRXJxrkxp8fA6Mcn9wGXHbMGfQdzvYmMVjp7uOEg+OXIaTk9TYNZHRGl4eup4XHi3xt3O/RVTvlVhTqQMPqnLf0ErjPQdYrIoiitQa1OSKwLBl3U6/FloHEi/CS8mAR5K2TQT3tS1R/GkX4riP+q6ej0Q3JsCqSqc4Cm41YJPh/pV5hITG5XdkbNRAQ5QRuvtWAsNTJqex/SX0vBXjQ8e3p62ycE7v+AYGEqyVMnbyvFTsYouviksoBQ6B3jyI6VdmgasAI2lKDQ9mTdLGwLQ5PwhIDV9Gaq3l89eZKHXl4qA+T1kmuIvxpxed79mAeZEVY4vInTRmsQH2jtM3A+kf92O4Pz0WLAbPOA+TIWC64nsUsrLCmPK2VqmfHxFfzkfeW9TzRuaKrokq3XekSfB2X6aLRMzWB09aJp+vUm+deGo
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
