apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
type: Opaque
data:
  CLOUDFLARE_TOKEN: ZXlKaElqb2lOREk1WlRNNE16azRNbVpsWTJRMlltRTFNR0U1WldGbU5tRmtOakkzTmpRaUxDSjBJam9pTldaaFlUaGtPVFV0WkRKaU5TMDBaVEF5TFRreVpUY3RPR1ZrTkdReFlqTmtaRE00SWl3aWN5STZJbGx0VlRCUFYxVjVXa1JKZEU5SFRtdGFRekF3VGxST2EweFhSVEZPYlVsMFQwUlplVTF0V20xWlZGVXlXVlJyTVNKOQ==
