---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCbubHTQBNIy7HElUbkvHUTn1kgSydhRNcx63Pkye8beaoCOSVZhgnbK8DSK13qM5tPGr05JEcKHXhmmyUBSK15HRRx6bSZrXlF0LmjCGSibuBkRGxLGOZAQ1fZXY+zh9gk/OeuoB2RUUSyhF0ZoUO7HwQ9oLVEG1Cwa8OA50Qv/QKC293om0Kp6TL+uKP4mt2+6IHRdml1fme8PBP4VBxRHsiZe6iNXlJIVyCZgVnmfD7pHlXcHoCK6BNdYWiWkbhmcCrAE5RUatoxNoHqHgeso3g+GMzlwJNzYyRbmgHa2DkyiM86thgwsjrRVJIjlRWHB8+duLYTZgQJ6oxkXlED3Mf95xFOFNLxFRe9HO7dbtjXQn2IvoFikmiRs5PtlDGgqYd4LDA37Q+yeOWILluHl8JxLpWs9LIhLpbs4akCHCRFQd2S+NVOmvK692Urezy/fWWRA/edxMroLoXQFmLOA4RYjL5ehupC3WyRDzP5sfUW1VppEtdJQ0rwpC9Sh+caUJSUe1mQUSUnE1B513y4IpUZ8MNgiH5nn3YLVgCZPFtcpyOlZpZYPcUQLTPhDAiBVG68/OMpiD+0RtLs0Jv592q1p76uhOao2lVZvziUZPZs8OgIEbSpqW08DcTZypWHwy/TDIXSfaS1K84ld/FFdXphwIQQSt95Gyi9L8/vkP2NeN7zJ2R4dGZSbeZcMnlnaLkd5NWKS94l4L3oAsAudda2wBdRP85C3YbQol2kyO/H0eOwNEdH6nwH6GGVgcB5px2OJQeWZjkMWFFXQ0uR41SmyOKxMWQ54YklngL3hRhCKlFUyh+8UiRSXnPMnC3lAimKCsDkLDT+xtgj21tniMb5rsyJvh7ddha1Bz9VuSGGXFr+7xSA7LzxkwLfNrm932tjB1N5TLParve7O/auxagPlBWNmDmFTNS2wY6oSsSqp37bBKxU
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
