apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-secret
  namespace: cloudflare
type: Opaque
data:
  CLOUDFLARE_TOKEN: ZXlKaElqb2lOREk1WlRNNE16azRNbVpsWTJRMlltRTFNR0U1WldGbU5tRmtOakkzTmpRaUxDSjBJam9pTldaaFlUaGtPVFV0WkRKaU5TMDBaVEF5TFRreVpUY3RPR1ZrTkdReFlqTmtaRE00SWl3aWN5STZJbGx0VlRCUFYxVjVXa1JKZEU5SFRtdGFRekF3VGxST2EweFhSVEZPYlVsMFQwUlplVTF0V20xWlZGVXlXVlJyTVNKOQ==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBC/fWHHSA1TKFgC8QvZv8CTkcgeyeqA0Uzhcr4p+NKQ96TQddOXEPe+yd1NsvvSwY1I03Px1uKar0VnWoIlGvNNJfU9rcv+zIYhtsTQ3S+ey/Km2EpwANO5epSf6F1Umq/BjCS0pJIDv5ZZjaKjhHMxHuzve9kB//Fi9iq6O6wjQFcOAyJe2b2y8rhKR/4ms0uC+1LFpHAdwhxzCIFF+lvPWhS0mba0Q61+hItSVQP7lEzjHpPJ9sha87ZK0tj3g1HXCwgZGLXtxrs+QJOru4YsolyVl0rJSoz3vs4nGI7cfhD2YdWesOjNhiDQsx40Iqbd2xsiMtUiPYep6I2KZDHA2W+5MC7fTJuc/qSkI11JDVNMWNaAGXZ9u6jtsfj28q4j/dUKO26MCIObTh3qIhFl9alHcEAzqt4ComZkQtbr6+RKeFjrElHjMy7KhYudu2rZCN67FYgVFhepSeYdl92dfTvh3WtYIQeA/5J6UkINuKyZ0rtJ6mZ6me1DM0pirkH3PTaYEvG+WzwiSi6PPqn3LbE+iQjiClEcM2zUZUTJ9xveswYb9FWdwzwhPNIwosScHXBuCNDjV9OuuPU6YZbYfzMLDPtm/VF0f5sXEMvA3y26HUMhJqmBLx8u3/VMU93kD7ECVxhMyZih37IkP6MEFTX5pv+ciUD3IY12xmv1J+oBWg8hQO+llLe2sXhCJN36IeY1zwksVJJebtsmLmvMJ52ldJHb4zq3RD36o6LCWsBsm76VsiFf2Fos/KOTholeVNvSKM0h8f3VrzVi8Ig2q5CX9u3+ZHCSccgXGh+qiNh6zT+HudnTWQ7Ijm3M8Co+pRBaQm4LVxfnu+9FXUSxOzVfTy6cEXF6IGRJxiTxpEIoQFQdtkHOB66wPLnNK0CkAaxIbALOSefBnVSmubH85jxAzkaHvC9FEjESGSmDPLrlOXAg6pY
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
