apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBvgvSReX/yZmqBQqQNbAnnrs4KhQNRxWpUm9WXwkwC7GbdCJIuATrCxSOuuUt+UlAqoITmD7KlW4rgNK+JosrlsCVE6yE0gqxYFS6tQa3akKmteIQMtTWiYbmaiPG7/u2CZcC1qg03D82eom91/4Gi/kb9S3J/8i9E8Karnrl7pPE6H+/6OD24YZP0WCmY6PM3DD03x1v7GdhWegoVPRs52tSsqeVlmNcLfLqbQwAiKgjqsSiEdUWTJf25rtTXimOdxw+IGzaiaPzqBTzuVNzu1d3TawDpvm9cd9MxvwKqsnkxqnnu51rs2yKF0kpfiJbbfPQBGOrfmq842BMbwT7VUr9QsIkJuyFVOgNZUc02NzZqbywloHElusVMENCfb1rQ32uz6zI37jBEHULlv0gsV4O7BxjYkh71SnynF5HVKVUGHHcaoG/jwpsW+ADro2uhvhn3wOLNGado30s0tJ35SMFAMjZG47h7m50ZrfIj4mKYsRtJcKC8aBvJDf9n2kUSvsl+5Ot5yRNqn6LOhAYvbx+7aS1szuaZCBF31bz8wYnRXnVkiD/M5Iop5TAOkgsVqhr4fBESX/vpF9tyEIe2wcsuXISWKKiGKU+PdbNEA6NCWukKizhBNsKr+IBMQupCuYdM8IyBXrBLyZnwt0rdEFGBCCy7e2TCMsDw2sM4HFn8vHg9Bz/PYFw5595jlXANoWFpir167apbhbRE1pNvB+bVuebDDPF9ekABF1HBx13yDpY29flQiYNHk6KcNgodgsG9D2D49TYq2jGyLGMwsHLv5MkMQAU05hsAlAVI0QHsOiM8gsvMjDeKCTJEVti7t9Tu+1Rztv8pfguJdh51L9Vqiq5rI3xo70U1hlt8OGdX0Z7hmJ2A8FGMZvlmCW5QVu4flpQhmJm4obwGq+N+O3w3vwa5OWHCHfpOpEA74EndFa3mVRqw
  template:
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/instance: apps
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
