---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBVbfxpA/Ml4+j30Mu9Q8jJm7XanDqPEEl2IVGVYRnFnhEF5Utmuoaz1w2OpQz/2j1fmlQqqIIQbtp3+MPQkCLKF68wgpUD19ts/Mliw+Uxh+awfl6917kuzKF3RKUAqTPVrGAogYbHOQ7inGkuRFCMqHN+c40Urmebv/v846/LkLCKAz1CGFzuzhrKLZ8+nBmhJUhfEqWi/uvJwb8KH+1Qll6Y/JoRJLJAHyTP/A0Ke8tdg/FIcrLpjPK/hYAZJnuXZ66nb7Wi4wvs1HWUov15eOLEafG/kHYz+wwutzIEwCRikmbfEuyG3mQb2Skf/IT03Ak4Z47rJjtv779/fImllA6lh+m3Lzyc6CuOjAI0G75n2hi6GBSXq1TsPO16rdxLST6XjYS35vVZEapcVRb9yxmvOqsYo+1bhpdhJgyU/Q76/ujd4cfzlca0VCzIILf2gwgE4Hd3vvduF3+y32n6od8Bw2C4fW0fqoMfUrtDbMSWKSaSiAfeuonwJZhzRuz5hSl6vX8WZVkAJxYa//x1sQqm/HyyMiAuTxKu6VmR3a8AzpjsuLGAAn34OznEqgzmprWDGZGaEUqmf5eeJYz90Nz7Vo0LrV0r7OiUAys15Ly+kwhvQxtFn5uHhQQGlK1iezdA5D41hF2VKs6zODwCviMEz/To4C31gZ6pPCh5yY2Zn9cwkPPSTr7p0rDRlmBZilbttMmzC1825YLBw2huHagtOP2XjhQInE9Qu5Y16g8QaA1km4rGad/kD2Msbf502hRA/S9AoMIk0QNjWxfsMPGPC1fZmXAXDBX9LDdOfVcAdVA646Y8wHANoJKbOvQdr6M+wv8mMIFwyh+rx7qCflAruQsrDTT4LR9zQix6VK+YW1zZdM+WjheD9GOAHGNEh7Pv51WAZ4O0EsB2f7P8fe6atxPFkFZQ8hUGFYf188Wtnm3jfmWu
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
