---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgARDKp6Afhv6Q+hKVs5x+UfeIvVSol+0aegDEKqmN5M50PIQs+tMuvU6bQIFgkQn3UkN3slXkeoARVKPkWNQ0xCXXjZbUnTBHoqa/QRNOZV6vuPqMurjK/EXB4SqxmVYeaqThqZ/4xKux+OE8nuNbjh4pN6EOJn7pMFTm0hShuFVQosgjd83zbssiVbewpwGPG9tApv7qg00FkJuTa1e9BZs8y4c1OJcClTGgFntJI9QwQX9HTtma0VsnLguZ3Ws+xNSLne6Sc9wa2HPBvxAxGySY51qUAOsVakOzdngGlbch/3mHlLAQgRjd/WNoh3VUcEp6VKlhwvqmTBVA736NfJbxn0xFFmrAkQDTD2B4rVLyFgmb10j6W5aL4gKet39n07y9mgz8igrvqgVCzhnoK8y1HDYhWptJ3L6Hd8N/oBeql/VFhGK5R+InAnjdrhFy4JJE7FxtR92ZOmhWak3ZR0GfgNnh4TDIB9XWuXUT0N7qyxRq/E11i1VkEI1XIkT30hpa5KVzMINV9acAI98b1IcsMpRyN6Ebp+Wl+uI6dUR9y4El+q6AyC6y+1waoZUG1vCM2uL8D6FWnGRXZt/ldqFgxpjc7moB4o68hJBQxTjY/YfvGq24VQZ3eqZdUt0nPBaQn0aQqapjZhRQeAhE5XwprSevdT2rvcwBdeHZuosdLicR9juwEgduVoO19J+NMTN2dE0xLJwppo5ipD5H/0Sv72AKQLjEtp90EkHH8BrcnMF4okeVQQBz3SibO/7CnCUdTaf/N9tmX0z1fFC8s7fdRGvDZ5t0x4UA883BqtoDBW+rS0UtKT/15atqklBpWq7+ByjhUnbhSypYnyqlnSHbsrFevqwxdqHCXNBRf2RGPxyUvbUereiomQmrRqjaZtv7yXKBpGJr3I9GMlcp03aBdT06ciwD0HaEZYzYl62ShLGkLPRDom
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
