---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgA8/CVG14U/xWmPlDH4riLu5hwWancNAefGbuSd1Y7j52ElcKM4lH92XAMtTgUmjdi3jnWd1OpaySmLjbiQF47tceEb9H5MEHeBuKRE2QRVlZschqp3+el7zlFbGV2DLr26agtGnfdz0R+zTIffe154h3utr9KjAIim3zIl/BldU1CsX0AD1xpxqtbtXFAQktR5Fsea3axGXq/uNN6JWK0xbkvU22uz7sc4DQFvD9Z9UYUBPJgB40fDWZbySuCHDuNwEqIdt25mf5IzGMVEG3Jfzmp7PXjeEcIU9RM8LfcQ8iqNPyyz5CbeeU23EOBkNQgAoLzxOQqLeZf7QnpeBvfrk7BbMZRgPQsUlxxmJgCecQh0T5XOiEUqRqQpCJFevmThMwM296NELTxo7e3kCaCMtCjEgL4q48WVDIi+ryEuOx7T7NrqvSziA5ow2wRg5X7UVE2/s590JSJCINZEyqmzXdKYOAoA0QR9AF39qKz58FJypJUnTWxaKim8ZAqPhy3JWPMLblFVcL+Ih+GpYAkYzrlHOm9PWNGkEH1auwGoiLaU+w6pKginRCuitK0ijev2/MOl/T/MbKbzSP4TY9zSU1gyUlmQLnnGt3RxzSuJ01okqUdXFetdx2hVv6chx0HzYBi0ITbxClTZcAbGqK2EOGD2TJAu8qxboc/SNHsKzz4uGbtWUlzU9GDSKGmJzSoVl6jT9Al3KvCSAegll3H0hySv/1bLIlPUYOJXC91SWvrp4gTjK96x69vyUfYUbdS/z4B72aentx2PhbosA0can8p4ahqct8nhjP+L0X0+HSFMFQt1nAOyjyD/R7OapOBHGziUTCQvbC1gcrcaUylDkjq5wMaawsdvSB2ykaFk0RUUOS0omTj7GJBHxV7fmdz1klFWPlsmxW2dvIU59WQ+IYAT3J8DpAOtTIV7IlHDLrChDbVqvDZD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
