---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: cloudflare
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCYNFeRl3SNdsig1LpXTzfDCckRLpGZ6SVSs7Sex04YhFAjCOIg+gFA8Xa6e4ZL5jsg3moOlbr7NRx4ZXxrEEUpZBMmz3ISiyCXrFW0nyFTUvUjZG+rwZyHjLN0cg03ZiAMgAj4nZHf7inwrVzIKdmYjgI1Sy8UZRYbMotqJeA+eGplR8pfEmnrNzRYfeRrNfBwDa7b/oPepHqbpOXC0eudqGM4R3DwJWfnFzXqVRJ1XRZCIrlOB0MsA6e7KT7TAkWoK0WJc6HKvHHv+GLztdIHAX5DJ0oiTm5uU2Gv3LwciYvWdOeldrWeDK8aqKwkN7JB5VqllNu+C7LEGK2A6X1CEbJHuo+zUkaeI7qqiJY0odE0DzK2JEFnhTKbIL9O6ljA47UEw+q05yngSuTEtjsDJipjijMxkiiRDowe4q5FJIaNfn6jPHB75KoYxiKQyYzujlu7JDgCe6jLMcF3lIBHfzvPaHak3QgM1SKJSMSrqhJarDm2JwKLHQFee5aVLfGi7MDUcQP4rr353xLV58wbe5gf/zQOL73WZiGI8c71SOUulUIG1OCcqj6sG1Yegxf7MkjaLa4EKIeWejFDih0Z3gz6FGAePve+dZKKKEX+bpJvGF1UU/iQ+WJLyUKCsQh5meGB/PG2FeJ1EwDcOwbYs+YkUSFaL1OTA5VbwyFDYovSNlrFB3jdfLS28wJ3zy0LuGlf8Q2BwG00yqfVK5rtGx1sdMOX6CRAKlxtkk4NemilXIBOTjbDyySg1++fFo2FWGqStAu3bdFR36b3K5vCrDOZiqMdL6rEWEImPQRf0r5Jltp+zOR5ihmsKB6tiaAlb4pX4S6L1cs6QIa81B/ncltaaA4lAiObxZiKpoT4mAm9RroHH6PGL9EA+tl7KQ6EfFAlFLpUZPACeIJy/QUDWIZDNpInWA/52jvdr/vtTc7TGfohp1/i
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: cloudflare
    type: Opaque
