---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBNdx5MmrniGbd41Bi3QPES8hOnZoxvi1zGBFoQZIcw4IsdACiGWhrRRoOY/NEA0wI/ZeW5P+ne4R3f/V/DIiKu4JRMXH+XHV2WM8BH/mqGtoh7fRkC6qkhxYISeQcrnGh4iSW/GtHC25GLRhGlVtjV2FZmO2ChUcOmZItv0TEIVRuBWlc/MNIp9fQ+5+68VIbsOUIaZQXM2LES3JD3iCUM823+WAo18SvOFsw51wSytk7qIrlCqTH/h6TbHosFGYHOsgLkII0oTftW660SqlD+v2ZU11l73E40gJtRlwkDxCEysWAFa/6ysE9ihtK0+94PWnRmsoIM2g0RVeRpoy/OEOhiKWbdbJXmDO0rdm8WWOnrVwXanNrsN295dERphXraGqE/SPQPoB2uGhr19uu1EIaI8q2gVfKfxCpg6miJxh+Lic81B5C/UYBeAecMm1TzfJF8oQRGdM7h4VaoILiFXTURKXmPjJZxlZOmPyb4GCxQunlg8+hjvNBSH0ZI9M4bgiwe0ja5q0iubXcrYEFxUI5uKaIBLbVoLlCN73wRfyJ45sCkmDss6J4m68Jb7dR5RTdJcREknctgJAXHOa5xy6dumU792EmduIsGmU5KlYj6t8uWDY3gLENK51bgr1up9XmidA6MHGCOY9Mqo+Xmw5AYuApohA82y38UmYg8IdvEbAvXzWZD4c1TuvPhR22UHytYPaaSHejE
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
