---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-phpmyadmin-secret
  namespace: mariadb-phpmyadmin
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgBhpySktON5wq+tbJIx9Y9xAjM0tjwsNtsjG185+VEygACKsYUIZzcbeqx2RL80fPlSvoUxef/c0qMxSTp7DIrv+AOUc/mN8+IHWYcg+bvizGne+lfhCAiELdVdqlPzvtlb0ojnmY+zAhvvw2iOeGETJlHvlS8iwFYfC21QF3i3hJfgOOOX80UIJQus7wBXG1OVm3CKfRdwzGKqC//SwJvgdFne/SxgQudJuoirDQLYHJtcs92CDqbdQpdfx/sCnBR5/al8OEbQ7iVkLfTJFv/YT6pK6lJhcXB3c8KlSBw6lEJEk4/heB/JDs69JXrByI3tS49NlDL5UUOF7FXAoRak8hyU/P3CqGtXDv54C5hX6Yf0fiY7zVGjb6vOxi7WzsVtAUPDbm3YQy7zMFIUyFeldB72OC5bOyQrqbI1ZXr4rIgozOmYQowYoOyrSjuO07EXV2EG2rtbZUGHui/X1KspAzQ7SG/MRT/2tY9MT3oE++DL0bk8eaoSyFyrO+pR67Kwa7MjgC+CB38K++b7bmEv7Wz2GQCX0Xsoj7cFFZCvl4iV2iJ3YoW76APvZToOsLIzFdDiITTLlhwb/i9c3AB56otLH5rxn0Yqdg6ba3goUrlKKqNdnv/qj/kl9C38M7ZCPMfy3QvnpTSZDNJzaDEQ8wpusTlmftF41Xu48jx0OBhq33l+45PqGRjzJulvlvQ1EiA4t7Nkyigj
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-phpmyadmin-secret
      namespace: mariadb-phpmyadmin
    type: Opaque
