---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-secret
  namespace: monitoring
spec:
  encryptedData:
    webhook_url: AgAgGmnFTy7hllUlHhvPSc/mpNiUEKXBgLcnVR/j/rSQGbVtYf1cT39xPtOaBAug/t1ZoVzBoECAr7g+xOBMSWQ+DnqQqXJ9w1HCa2DZVK4EMfyu85V5IbNR5NRXd39zdp856Gs5HhIsPzFMyZgPhA63Ssmy2+fhZ22/Su65592bMzvwzAvkFH6mbXIvrZAfeAJvwV08ztqsNkVss792koib6GuuxdsdMzTRnpCqMmtpC/sDs93A/tHWBJTdBZoXVxAO4PEAEtQ1ioKzO+y1b2KunMqq0xX+fMtyIMDgR12JwQ5G2CuEyNnaVGrxCKyYjuMvbPfQtVXSqtSiadI9s96Q+v1WUm/z5qgvqPzleH4HetWCgNcJ0rZ1S682f7aOrmjFvdsn9h2pDV+fKvFFwkcPd5/EOUQHseD0g8Rajm+zI4RoQdYyjiLhDSKQHBUKdqc+NgRAVFwz8LtOHIgAsXi+wZ+LYbFDK8abEK/XNbL77rRpGnaFlKRaxT6Hikac27xxmYE7yJxprxXXVmfaYZu1pvBYdYWm/n7udjzASi86H13C8s/Nwk/tTHoELyOpULyJW6ofIm3zNykxPYAmh7E4d+1WyCoo0AqN1hmT50WdVgsHDjVRFP7jYF+vBr2jWvNUCs/7xg7NMP44wv4WkTuXhHga/AJe2ysXxKiZ95ShKwLPC7qEF0vWwMFzBaitwBKuPko+6+tGAe0hz396+Q73sJdrAnMgvMUIuE1STPjAJ174alJ89d7bg4aGitI5B8prpcRApwWRx1yvHPg0POS9L4qgEPNCqtnD2mmIFB/XduScuVuyPCaQMXUg6vHOQ4vmi4fle177QI8+kmWiGW8QyMSr2zx9NPcV
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-secret
      namespace: monitoring
    type: Opaque
