---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: monitoring-secret
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgBeaVQHVOtJBLQ9ots4xaLVDAFdseqxX3LExB53xbNMxCESvby/pR9VAKIDtfv457HJ462Ev1rIMalVuki1U5PKhvobF4NPrjsGDMj7FnUONAJKLbBhXjAxZxG7U5qJNHWvqm868Uf+XkQPwC11st9BVCoFwlPRcuU6e9S+5apPaY7aSRpI+ziZxQqkqWvPkoqp39cb/X6loukm3BPFtNJkMbfdM8j0q5/sEDrtPFAXoS2rxldAoyOqI+62REPnmhYACj2VZLbQj++irQxsQfCfgpuhmGaNbI23V1ojbOQsuoi7IzR2RAUhHTWgevWt9ZRpGhqGZlTigrwD2iR2CEP+FFLDGRAFqVGYZi/bQ3HJsI3oxeQ9ywN9mjtYg2VxI/Dc3bEx81KWlgKnVgK5+LIyH5opUd4A//Y+6dpKEH8Wmac3xtqsumgo4hdAwYTmLGeS283+n9KPHskjqPw/ZwohVPWuij+0zTLYg/vgr+ueO+vfcpj+r0XWloVCHRnVRpPBSPz/itc1mV5kdITJMxUmijKgwFgqMAndskTwh8Bah4IavcIxKyD5eRFSkTFex5m594g7UQbT9m7X2VsOrVLBq+ZT+3N05bwp+CMqvZXXs2E80Hir/FD+jBfpGGNcBMms6uxVEk0zKy6bq9gHREDEtXYNSRvQuBhXDRsks3k/kKvbl2OToIxWf/8bpUmalaIDYPk6tN1qhNRD+1JzMai/IhdqGd35zhXuy6zXVUe/mnOeTEVHfolfZxldtyuK3Uul3+dhSbHb3w9pl5LhEoOaZXi7W1BfKIjJ9INUvJ/iWcvZ2jROGViUQfqGk56iC/2cwtUSU0p4Q6HFggeGXeKlZes4PY54ajbV
  template:
    metadata:
      creationTimestamp: null
      name: monitoring-secret
      namespace: monitoring
    type: Opaque
