apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: monitoring
type: Opaque
data:
  webhook-url: aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTA3NTA0NTQ2OTUzMDY0MDQ0Ni9VR2I1YXByYzkyNW9WVWpvc1VxYmo5X0QxTVBZcVp2REhYaHdKM3FlQmlTUWx2dVJOM0d2YVJSSzhFRU1JT3BnZVlNag==
