apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - directory:
        path: apps
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:Gamer-Iris/MyServerTest.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
