apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .Release.Name }}-alertmanager
spec:
  replicas: 1
  serviceAccountName: {{ .Release.Name }}-service-account
  config:
    receivers:
    - name: {{ .Values.alertmanager.config.receivers[0].name }}
      discord_configs:
        - webhook_url: {{ .Values.alertmanager.config.receivers[0].discord_configs[0].webhook_url }}
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.storageClassName }}
        accessModes: {{ .Values.alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.accessModes }}
        resources:
          requests:
            storage: {{ .Values.alertmanager.alertmanagerSpec.storage.volumeClaimTemplate.spec.resources.requests.storage }}
  nodeSelector:
    labelname: {{ .Values.alertmanager.alertmanagerSpec.nodeSelector.labelname }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
spec:
  type: {{ .Values.alertmanager.service.type }}
  loadBalancerIP: {{ .Values.alertmanager.service.loadBalancerIP }}
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: {{ .Release.Name }}-alertmanager
