apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      nodeSelector:
        labelname: {{ .Values.grafana.nodeSelector.labelname }}
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
        - name: grafana-image-renderer
          image: grafana/image-renderer:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  type: {{ .Values.grafana.service.type }}
  loadBalancerIP: {{ .Values.grafana.service.loadBalancerIP }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}-grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-pvc
spec:
  accessModes:
    - {{ .Values.grafana.persistence.accessModes | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
  storageClassName: {{ .Values.grafana.persistence.storageClassName }}
  finalizers:
    - kubernetes.io/pvc-protection
