apiVersion: kustomization.k8s.io/v1beta1
kind: Kustomization
resources:
  - templates/monitoring-namespace.yml
  - templates/nfs-sc-monitoring.yml
  - templates/nfs-pv-monitoring.yml
  - templates/nfs-pvc-monitoring.yml
  - templates/monitoring-custom.yml
