apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: alertmanager-nfs-storage-class
  nfs:
    server: ubuntu-102.server.com
    path: /mnt/share/k8s/alertmanager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: prometheus-nfs-storage-class
  nfs:
    server: ubuntu-102.server.com
    path: /mnt/share/k8s/prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: monitoring
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-nfs-storage-class
  nfs:
    server: ubuntu-102.server.com
    path: /mnt/share/k8s/grafana
