apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-thanos-ruler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-thanos-ruler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-thanos-ruler
    spec:
      nodeSelector:
        labelname: {{ .Values.thanosRuler.thanosRulerSpec.nodeSelector.labelname }}
      containers:
        - name: thanos-ruler
          image: thanos-ruler:latest
          ports:
            - containerPort: 10901
