apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeseal
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeseal
  template:
    metadata:
      labels:
        app: kubeseal
    spec:
      containers:
      - name: kubeseal
        image: bitnami/sealed-secrets-kubeseal:latest
