apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets
  template:
    metadata:
      labels:
        app: sealed-secrets
    spec:
      nodeSelector:
        labelname: ubuntu-302
      containers:
      - name: controller
        image: bitnami/sealed-secrets-controller:latest
        ports:
        - containerPort: 8080
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  group: bitnami.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                encryptedData:
                  type: object
                template:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                    type:
                      type: string
  scope: Namespaced
  names:
    plural: sealedsecrets
    singular: sealedsecret
    kind: SealedSecret
    shortNames:
    - ss
---
apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sealed-secrets
