apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sealed-secrets.fullname" . }}
  labels:
    app: {{ include "sealed-secrets.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sealed-secrets.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sealed-secrets.name" . }}
    spec:
      containers:
        - name: sealed-secrets-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sealed-secrets.fullname" . }}
  labels:
    app: {{ include "sealed-secrets.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "sealed-secrets.name" . }}
