apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets
  template:
    metadata:
      labels:
        app: sealed-secrets
    spec:
      nodeSelector:
        labelname: ubuntu-302
      containers:
      - name: controller
        image: bitnami/sealed-secrets-controller:latest
        ports:
        - containerPort: 8080
