kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-pv
  namespace: wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: wordpress-nfs-storage-class
  nfs:
    server: ubuntu-102.server.com
    path: /mnt/share/k8s/wordpress
