apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_NAME: ご自分の環境に合わせてください。
  WORDPRESS_DB_USER: ご自分の環境に合わせてください。
  WORDPRESS_DB_PASSWORD: ご自分の環境に合わせてください。
