apiVersion: v1
data:
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: aGlrYXJ1MDYwOA==
  WORDPRESS_DB_USER: d29yZHByZXNz
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"WORDPRESS_DB_NAME":"d29yZHByZXNz","WORDPRESS_DB_PASSWORD":"aGlrYXJ1MDYwOA==","WORDPRESS_DB_USER":"d29yZHByZXNz"},"kind":"Secret","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"wordpress"},"name":"wordpress-secret","namespace":"wordpress"},"type":"Opaque"}
  creationTimestamp: "2024-10-16T16:04:59Z"
  labels:
    argocd.argoproj.io/instance: wordpress
  name: wordpress-secret
  namespace: wordpress
  resourceVersion: "138332"
  uid: 7f5d673d-7e62-49ee-a7b3-0407a7acfbe7
type: Opaque
