apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_USER: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: aGlrYXJ1MDYwOA==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wordpress-secret
  namespace: wordpress
spec:
  encryptedData:
    WORDPRESS_DB_NAME: AgAjzdHNY0NE4zD4Nn2dSk0qezp7XcQoRMKe/BkFcLGaw+uLW+IZA7cYrSCLRLt+m5XS11C9zrhfu/gbKAh6PkyTdr384cV6qPwdlBWm7ePLMWiyWbfWwIpDvaUBp9zB2lXnyeUQB+I+wfdv2ni2bilnUXuJwE5L1cuDl8Pb3/6l1jcs5h1H4njb0xAAGkFXINvSXjTbPSez4j22XWZ1CV4NTI4CtJeEKzcYkjSbXcV4YgS9pAhNOnb7b3JULUAB53dzbdUhutIIi3PK8GZigzOWScWw7c4alS+8GHJdVm8jI1kLwHUDmk46wmLtewObbG2c8qCFcg9vDKzzUK+5kt4IF2fyrI0oKYXdHkGuZPXEt0IyNxFmknpeV8zPCcygKIJlX7Sky4wiuozXvLyOvprN0dSF5LR+6UEh1Wp3kn/HxQ6ETjzIQihOHS9SWGtYhjvda4Zkh8vbKMH599ZfxOTDkCQNuAcNZDMYYjd447QjWh5gkWorYEhlYwT7wC/iMGy7CVwV52bHAk/m9f3AMGR0FWfztXKMudKFfQZoTjPD8FiEkoVvdC66DUSO2GM7ozUVJ8MQGSeJ2+zGLuF2wOX79cWOUlt5K4qEKogRyNZEWI7HpJoQcHYgkf3lfEaKJP7yu0B/ogPbkmVBC+tr7aJgJTpn/Q/NA4+Qwg0GUS/ofnfw0ExLsJr+lHXC3WjU6c2cYhOVqocoX4U=
    WORDPRESS_DB_PASSWORD: AgC0N/HEqMDMK33GdJrHzDDtbHJmkLKx9Z3m/Bv3t+BI4RgWgVBxIckcvJdVRHWVWWk4uGD2/pgemeUvgSacHQok2ogrIAcaoSyaxvoAzd3OlkADrIsILvFvDKo+/ogFR+9ErgB2wKbbigF7IUEImbhIsoEpu3NCKiqdUZve1at5LQ3P0xikSs0YcJkAUQeWy9OBlgmRZ88XHfl5rIJRFY94V9rLdbCobO9U4kE34YGd/06nbPJ7BGaDOyCurTbH84Q3Ww0/3rE3H90Lm9nF7Rix9ZFz6pCHpJ56r73tb+uwTgTtMYDs/QaWFfKNlxU/MQYqgY/PGpWpuYeHWwtkAO6ILDH84ktxHg/T+2kmcKW1jd3yjph52Xh7T3hnFNSfaRmDPAqifnhh6O39WzYBg7e/3VretSXtfBwb+hKk8jVS4JZKiPnTqaUwc6bOzRMPK6MqsUiB48hfT6V1Wru33G6M7J+IPAXjvmX6dWXPqfXlB2KmxiHLWCyTzRzGV9zUOkomxmF9Jh0xZxSTwIkYmxd8Zgx76v/fj4rXzes/aY8yWHGR7A03CDe/eYs3phI7Ww3PH6h51Pf5dIIoI/xFdovsTu2CBh7xMQk0cq+3KAdL715BRLSDdR6MMDtelk0YJYbk3CM952RhNCHlqWKQKlHl5xP75ruDO31ZxYFKgFnTw58WjxwXhjyrdGkxn1sbaTQnni/uLkvBWy8J
    WORDPRESS_DB_USER: AgBLM62hHue/iBPS6i8qMmleZsWbywgTDDTNmi9iOxuOUlDLHvQCKsIzOlLkx8RL9ctU555xGzpJTA9lRLK6nVTx+h6CugpEFdznVuES/fKY1xnj17psXaU/E8ckoBG+552YuFxMmNr+jaPx3kM2mVEZ08THlC8b5/JNhrLxG7OR2MsPa/6bDk2kq2f910i9/ls2ASBJKz1hHjPxtjwwvB2LPVwgvgSucAIeMYd6cEdYBMQ0wjhCdE/9Wdg1hIDN93G+2v5QH/Xk1ub6vIQ4pcS6DkEN+wPjhcvbHH47pFyVO3nK4L5olnIPQMGAR32af6+F0PtZgdih3DEBk3vtYiMpQnlfV6ALmhMqiv4wSrLfEp8jHaGtYiMJ1dc9hv8xpEqo3AhsmXgxGRK9PeyOJk+hxsMetsUn16bpVFrtUxeTZ2GqitNrYHVX+mIG7L0F8qBlzi7wXsvBKAMQtYScvdL/eMaHiW1Hs9M9Bhlosw7zUUE4bv8x64UquxiMoFGBtOMLyYSK7MIBdvXeIUHjjcjep84xGSXFnVWkIg+Q6D3XfT1p4K93xfgQkz2jD8yW7KUrpONR4YNqcYv+KUhjoNzqNxpQmZPDr0uLpuJSclCRltwBJTBQ/BejvdUhmi3kDzE57cHzCLJEpW7pGNtIE48BpXRlJSxuG6Jn5HNWi9WceL1Me991JJtOPcQ6+WgrG8R7176i1Gd8MFg=
  template:
    metadata:
      creationTimestamp: null
      name: wordpress-secret
      namespace: wordpress
    type: Opaque
