apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_USER: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: aGlrYXJ1MDYwOA==
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wordpress-secret
  namespace: wordpress
spec:
  encryptedData:
    WORDPRESS_DB_NAME: AgCnlwAUv4uv8mr0VHJut+knUwic0i62Z/EmHgRpq/1QysvitSC2Hk/hwOj2YoPzahRI0alSBF7G1cxkyr4E8GCPyIuSQYihsXlNvAHSeynpoEHy0NaWrduXutsS5tBAlAsg/KBK0gesCZRUwHCNdQ28avJUa5G2GOuvLNusOra3e8qJv7SVWTuBEVLOotmQbpjZCUPU/7mtbrFwrx3qY/LlEv0crwsECEhmg5Lem8LfNW8/KXOVU03h+4/sxXCSCEcVlTTKRUuLL0EogT58399fE/cr7gNry7t49WZ7FzLlZ/UyUMtkPFyBu8kpMShAKnAsUhO6pSF0l+ViKlPqChtG51CvK9ElgWQyantQTKo6ng9dxzaoe8oTEB1wIu9ntYk99cHx4izR6AK2I2/elhl78p39AGblx6WaSKlCYOUskrGPY8D1SNCodm4a3RAvWB+EGW/0BVGscdQW2PHWEa45ow66EZxx6fF9KnUDXUSQdRS2NtTaqwLBDfBRX3g36TJLmD7Ds3rMkm3OiAA9RoMEur9IuupT65zuNyQH1NLjE9Fx47q0iZfw9qFPEcPJVbItpRL8+PoCYxV9VgSZNnuMsswG9+PbgjzZeEMi3p7IC2RPNCNnKqyVs5Kwv88gwburrSJheuEQGq/ZmAT45eZpObMLmRCKeOiigSQURO2TTyKcmH/pUc/Io70nUOn5SMpfSXJELWIfZF0=
    WORDPRESS_DB_PASSWORD: AgAPRzh0W5lK3j0hOmxCMMDXbCFZV2oUGCekpMXfWf5dRD1nVYLpv/7/BBqUPjGrpf/DpDr5wYew0adIsVEZd6cTaPpK/aM0ascXIa2T1jQz7Zp/J9lKUI+l0aulUiFNPeXljE1QEKfHggAwPGvO4HWvml3eOzo6y5Ee0Zly5zAeA2MttOF2IE+Hn5FiPs/VLgxR0cSLFkZ4cQlDFPogSlxU0uWpHo25Zs20PJPKj2z3P156S4vGGTt8IU3hSlzz8ilcwt3FKB7HMPWLOXM1fyU1Vv77L+wouVFgSzvTeMI1LYW+GmLKHTfgoQQoWI2yT2ZGF3WTo02YDLC3Lh9ixyj/rQYuTNNWYVG5/6AaWuCH7y38lJ7rlZ3UG14P+x2SSlPbjW8WxyJu4rSRU8BI13U8CKnxrbU4ttewppDCkbsLZZaghnRONDPmkfK/ZrvduFfE7ESem1e/Md6bF1zRvR/yGu/wgPh2cdH4rX8o0my0NnfoyZxHJoxqbERB3QM4wjVcX08EMrCZDjPsc9L4VhbJzS1KNHijRp6RI+nVsRQQY0pFWfYle/xRui+7mAIi4aNzehDmzNmXUmOmPRwPuXzbuHA0pzzqnTcO+87JzPPkYgc4er9uBRXOqlgGdKvZW4bHVKmqHxnpjOrABf31dM0swNJwl1bO6aoLxCnOy4X9p++dzUDsOepjPReZaCI/7tUq0c6Hweu1AL+b
    WORDPRESS_DB_USER: AgDEsrx6JejV0nH9QL8KTiWL+VNT4gfw4bZzWDvZgobHtz0RnRYRKjQUgETHyxynEfYt1gDvGOZyf9MX4tAdgTsq/FD+m9PvtqPGQ3YZougNfzpPBdjOkNcYApJa4qB7ojeKZLiK0LO5k7Gsxg/lH6xDgNe2hoV0lQjMvlbzFBuV7JbL/wdt1yQZRHPU6SRr45MB0i/fb3sAqK6T+lk4jX41P4KzaIgfnhKFpCyOVX0ZY77Cs1izRQT6/TiQmL2mH3T8MXOVX313RsZpM8Q5WYqPBDxqiBe1aFNHam3ICP575xoq4CA8c/kCPkKZO9C6at05Rp8Wz0CTPUQbZS/4HkZptFvN4Hx79+9PGR2o8k1UCQPWsUF2d+1Btdl37e7Q4aj6ZfsL8ibOkb+PjSpr83kpB/UC/AjcACiXXsQcMRT7dRg/XeskpLpFcGUdYxAdOg5JsPy0ufSFfgmk3e17LDGXRiQPx/tWhtRhGchijssLULXJsr4BpdVajFlJIJ3g8kWu3kUCUuAKKVlSpaZ+1KnxS9VIhZVkbTAtJYdbYrsL2ZQ7knSFYGhm0fzjnSPxeXN+NgN/wYIzAdG9DW59CkZD2lxksa//AR5m3fLaMlXEUJaur1uh/CiohyvewwCH29ZtCb9PJTomgmNGPHcsxzKgOldt8MYS8t2asBJD9FRhe0YhbEDfJ/uHHcv93TqZG8baEVbm3zyB5nQ=
  template:
    metadata:
      creationTimestamp: null
      name: wordpress-secret
      namespace: wordpress
    type: Opaque
