apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_USER: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: aGlrYXJ1MDYwOA==
